name: Terraform Plan

on: [push]

jobs:
    terraform-plan:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Minikube
          uses: manusa/actions-setup-minikube@v2.13.1
          with:
                minikube version: 'v1.35.0'
                kubernetes version: 'v1.32.0'
                driver: 'docker'

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3.1.2
          with:
              terraform_version: 1.10.5

        - name: Initialize Terraform
          run: terraform init -input=false

        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color

        - name: Terraform Plan
          id: plan
          run: terraform plan -input=false -no-color